import Navbar from "@/ui/Navbar/Navbar";
import StoreProvider from "./StoreProvider";
import "./globals.sass";
import Footer from "@/ui/Footer/Footer";
import Cart from "@/ui/Cart/Cart";
import favicon from "/public/favicon.ico"
export const metadata = {
  title: "MolenBike",
  description: "Generated by create next app",
  icons:[{rel:'icon',url:favicon.src}]
  
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Navbar/>
          <Cart/>
          {children}
          <Footer/>
        </body>
      </html>
    </StoreProvider>
  );
}
