import Navbar from "@/ui/Navbar/Navbar";
import StoreProvider from "./StoreProvider";
import "./globals.sass";
import Footer from "@/ui/Footer/Footer";
export const metadata = {
  title: "MolenBike",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Navbar/>
          {children}
          <Footer/>
        </body>
      </html>
    </StoreProvider>
  );
}
